### ISSUE TITLE
fresh installation on trusty, but failed to configure ion-dbreports

### ISSUE THREAD

**Issue by biocyberman** [iontorrent/TS#21]
Hello
I am trying to install TS on Ubuntu 14.04. I enabled binary repository on `http://ionupdates/updates/software trusty/` and install all ion-\* packages. All seemed to go fine, only `ion-dbreports` and `ion-plugins`, which depends on ion-dbreports, failed to finish their installation. 

I check posgres databases and users: no user named `ion` exists, and no database named iondb was created.

``` bash
ionadmin@testts:~$ uname -a
Linux testts 3.19.0-47-generic #53~14.04.1-Ubuntu SMP Mon Jan 18 16:09:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ionadmin@testts:~$ sudo apt-get install ion-dbreports # THIS COMMAND TRIES TO RESTART CONFIGURATION OF ion-dbreports
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ion-dbreports is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up ion-dbreports (5.0.19-1) ...
postinst configure 
/usr/sbin/update-python-modules
Adding password for user logout
Module wsgi already enabled
Module headers already enabled
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Module socache_shmcb already enabled
Module ssl already enabled
Module setenvif already enabled
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
Module filter already enabled
Module expires already enabled
Module rewrite already enabled
Considering dependency mime for include:
Module mime already enabled
Module include already enabled
Site 000-default already disabled
ERROR: Site default does not exist!
Site default-ssl already disabled
Site torrent-server already enabled
Site torrent-server-ssl already enabled
Conf h5bp-server already enabled
Conf torrent-server-config already enabled
 System start/stop links for /etc/init.d/ionCrawler already exist.
 System start/stop links for /etc/init.d/ionJobServer already exist.
 System start/stop links for /etc/init.d/ionPlugin already exist.
 System start/stop links for /etc/init.d/celeryd already exist.
 System start/stop links for /etc/init.d/celerybeat already exist.
 * Stopping web server apache2
 * 
celery init v10.1.
Using configuration: /etc/default/celeryd, /etc/default/celerybeat
Stopping celerybeat... NOT RUNNING
celery init v10.1.
Using config script: /etc/default/celeryd
celery multi v3.1.6 (Cipater)
> w1@testts: DOWN
> plugins@testts: DOWN
> periodic@testts: DOWN
> slowlane@testts: DOWN
> transfer@testts: DOWN
> diskutil@testts: DOWN
> dmprocess@testts: DOWN
> dmmanage@testts: DOWN
We need a superuser
Syncing...
Traceback (most recent call last):
  File "./bin/initsprusr.py", line 52, in <module>
    createSuperUser()
  File "./bin/initsprusr.py", line 35, in createSuperUser
    management.call_command("syncdb", interactive=False, load_initial_data=False, migrate=False )
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
    syncdb.Command().execute(**options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
    cursor = connection.cursor()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 159, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 129, in _cursor
    self.ensure_connection()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 112, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 116, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "ion"

dpkg: error processing package ion-dbreports (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ion-plugins:
 ion-plugins depends on ion-dbreports; however:
  Package ion-dbreports is not configured yet.

dpkg: error processing package ion-plugins (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 ion-dbreports
 ion-plugins
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by biocyberman** [comment]
Running `TSconfig -s` and  `TSconfig --reconfigure` also failed.

**Comment by uma-ramasubramanian** [comment]
Thank you for reporting the issue. Please follow the below support channels based on your region for further support: 
ngs-amsupport@thermofisher.com (Americas)
ngs-eusupport@thermofisher.com (EMEA)
ngs-gcsupport@thermofisher.com (Greater China)
ngs-sasiasupport@thermofisher.com (South Asia) 
 jptech@thermofisher.com (Japan) 
APAC customers, please contact your local sales representative, Field Service Engineer or Field Bioinformatics Specialist .
